Missing migrations handling. BMP-596
mc2soft/goose pull request #1
Opened 2017-10-04 16:41 UTC by Stepych

2017-10-04 19:40 UTC, kaey commented on README.md
> +                         Warning! Do not use any other up* commands after this!
почему?

2017-10-05 08:06 UTC, Stepych commented on README.md
> +                         Warning! Do not use any other up* commands after this!
"Версией" миграций станет последняя из накаченных этой командой миграций. Если повторно запустить эту же команду, поведение будет ожидаемое - будут запущены только новые миграции, если они за это время появились. А вот есть запустить, например `up`, то накатит повторно все миграции после последней из пропущенных.
Пример: есть миграции 1, 2, 4. Дернули `up-missing`, они накатились. Потом появилась миграция 3, накатили ее также через `up-missing`, все хорошо. Но версия миграций стала уже не 4, а 3! Так что запуск команды `up` в такой ситуации приведет к повторному накатыванию миграции 4.

2017-10-05 08:29 UTC, kaey commented on README.md
> +                         Warning! Do not use any other up* commands after this!
Говно, надо переделать. В бд должен сохраняться список накатанных миграций, последняя версия должна определяться по order by version limit 1

2017-10-05 08:34 UTC, bikbah approved these changes

2017-10-05 09:05 UTC, Stepych commented on README.md
> +                         Warning! Do not use any other up* commands after this!
В БД хранится список действий с миграциями, например если было несколько `down` и `up`'ов, то он будет больше, чем количество миграций.
Если определять последнюю версию по максимальной из существующих в этом списке, то некорректно будет работать `down` - после выполнения примера выше, `down` откатит 4 миграцию вместо 3.
В целом, `up-missing` - это альтернатива другим `up`* командам, работает она корректно, и проект сам выбирает, пользоваться ли ей или старыми командами. При этом, если выбран `up-missing` (как требуется нам), то все остальные команды будут работать корректно, в т.ч. `down`.

2017-10-05 09:08 UTC, Stepych commented on README.md
> +                         Warning! Do not use any other up* commands after this!
Т.е. у нас про будут зашиты действия команд `status-missing` и `up-missing` , и все будет работать в соответствии с требованиями. (см. https://mc2soft.myjetbrains.com/youtrack/issue/BMP-596)

2017-10-05 10:59 UTC, kaey commented on README.md
> +                         Warning! Do not use any other up* commands after this!
зачем было форкать тогда эту либу, вместо go-pg, если есть такие ограничения?
неконсистентное поведение меня не устраивает, тем более что кто-нибудь когда-нибудь придет и накатит миграции тулзой.
да и в апстрим такое не примут

2017-10-05 12:38 UTC, Stepych commented on README.md
> +                         Warning! Do not use any other up* commands after this!
goose умеет sql-файлы (в которых сейчас все миграции bmp-api, и которые проще и удобнее писать с подсветкой синтаксиса)  и go-миграции, а go-pg только go. Поэтому я выбрал goose.
А по поводу поведения - в go-pg будет то же самое, т.к. накатывание пропущенных миграций и там и там изменит версию. Чтобы избежать неконсистентности, нужно либо убирать стандартные up-команды (или заменять их), либо в базе запоминать, что мы перешли на другую логику миграций, и блокировать их.

2017-10-05 12:44 UTC, Stepych commented on README.md
> +                         Warning! Do not use any other up* commands after this!
Я вижу единственный выход с сохранением консистентности при накатывании пропущенных миграций, например накачены миграции 1, 2 и 4:
1. down - откатим 4
2. up - накатим пропущенную 3, и заново накатим 4

2017-10-06 08:21 UTC, Stepych commented on README.md
> +                         Warning! Do not use any other up* commands after this!
Обсудили голосом с @upovod и @ImmortalIC:
* вместо отдельной команды `up-missing` заменяем старое поведение (убирает неконсистентность; и для пользователей, у которых не бывает пропущенных миграций, ничего не изменится)
* вместо `status-missing` добавляем к существующей команде `status` возможность указать флаг `--missing-only` (сейчас `status` выводит весь огромный список миграций в базе, а с новым флагом он будет работать как команда `status-missing`, т.е. выводить только те миграции, которые еще не были применены)

2017-10-06 10:00 UTC, kaey commented on README.md
> +                         Warning! Do not use any other up* commands after this!
> goose умеет sql-файлы (в которых сейчас все миграции bmp-api, и которые проще и удобнее писать с подсветкой синтаксиса) и go-миграции, а go-pg только go. Поэтому я выбрал goose.

это кода на 40 строчек - filepath.Glob + sort.Slice + ioutil.ReadFile + InTransaction + sql.Exec

>А по поводу поведения - в go-pg будет то же самое, т.к. накатывание пропущенных миграций и там и там изменит версию

нет - go-pg добавляет номер миграции в бд, если она накатилась и ничего это не ломает

> up - накатим пропущенную 3, и заново накатим 4

так нельзя

2017-10-06 10:05 UTC, kaey commented on README.md
> +                         Warning! Do not use any other up* commands after this!
и еще момент, нам изредка нужно откатывать релиз и откатывать миграции, сейчас мы ручками делаем psql -f xxx_down.sql, в случае с гусем это не прокатит и нужно ставить тулзу куда-то? или что-то еще придумывать

2017-10-06 10:43 UTC, Stepych commented on README.md
> +                         Warning! Do not use any other up* commands after this!
>> up - накатим пропущенную 3, и заново накатим 4

> так нельзя

Этого не будет, т.к. договорились менять поведение, вместо добавление нового несовместимого.

> и еще момент, нам изредка нужно откатывать релиз и откатывать миграции, сейчас мы ручками делаем psql -f xxx_down.sql, в случае с гусем это не прокатит и нужно ставить тулзу куда-то? или что-то еще придумывать

Можно добавить команду прямо в bmp-api)) По аналогии с твоим требованием
> при запуске bmp-api -migrate они должны накатываться

, сделать например `bmp-api -migrate-down`.

2017-10-06 13:58 UTC, Stepych commented
Заменил старую логику миграций новой.

2017-10-09 09:37 UTC, Stepych commented
Добавил флаг -pretend к up*-командам - прогон миграций без их выполнения но с обновлением БД миграций - нужен будет нам для первого запуска миграций, чтобы goose знал, какие миграции в базе уже реально есть.

2017-10-09 15:16 UTC, ImmortalIC requested changes

2017-10-09 15:16 UTC, ImmortalIC commented on cmd/goose/main.go
> +	missingOnly   = flags.Bool("missing-only", false, "for status command - find out only migrations, missing from the current DB")
gofmt

2017-10-10 08:25 UTC, Stepych commented
От @upovod: не нужно убирать команды, если хочешь в upstream. Так что буду возвращать команду up-to.

2017-10-10 10:02 UTC, upovod commented
Лучше вместо странных прогонов в скрипте миграции одним SQL перенести записи из `schema_versions` в таблицу для goose.

2017-10-10 10:40 UTC, Stepych commented
@upovod я не очень понял тебя насчет "странных прогонов в скрипте миграции одним SQL", можешь ткнуть меня в код?..

2017-10-10 16:05 UTC, Stepych commented
Комментарий @upovod относился к моему предыдущему комментарию 

> Добавил флаг -pretend к up*-командам - прогон миграций без их выполнения но с обновлением БД миграций - нужен будет нам для первого запуска миграций, чтобы goose знал, какие миграции в базе уже реально есть.

Отвечаю: ок, жаль мне это раньше не пришло в голову) Но возможность получилась прикольная)

2017-10-11 17:25 UTC, ImmortalIC approved these changes

2017-10-12 08:09 UTC, kaey commented on examples/go-migrations/main.go
> +        run migrations without applying them - only update current DB. Accepted by all up* commands
а это зачем? отличный способ бд сломать

2017-10-12 08:11 UTC, Stepych commented on examples/go-migrations/main.go
> +        run migrations without applying them - only update current DB. Accepted by all up* commands
А это уже обсудили - см. https://github.com/mc2soft/goose/pull/1#issuecomment-335424174
Если вкратце - у нас это использовать не будем.

2017-10-12 10:30 UTC, kaey commented on examples/go-migrations/main.go
> +        run migrations without applying them - only update current DB. Accepted by all up* commands
тогда и не надо это добавлять, это очень странная вещь.
не нужно делать фичу, если у нее нет юзеров

2017-10-12 11:01 UTC, Stepych commented on examples/go-migrations/main.go
> +        run migrations without applying them - only update current DB. Accepted by all up* commands
Насчет странной вещи - это примерно то же самое, что в используемом сейчас в bmp-api https://github.com/mattes/migrate/tree/master/cli - там есть `force V      Set version V but don't run migration (ignores dirty state)` )) Я сделал по аналогии, чтобы нам можно было удобно имитировать накатывание существующих миграций. Но потом @upovod предложил сделать переход на goose запросом в базу, поэтому мы не будем использовать мой `-pretend`.
Я считаю, что выпиливать эту фичу нецелесообразно - я опять буду возиться, потом опять вас всех буду дергать на ревью, и все затянется. А то, что у нас нет юзеров, не значит, что их не найдется в апстриме!) Да может и нашим форком напрямую будут пользоваться, еще до апстрима.

2017-10-12 11:14 UTC, kaey commented on examples/go-migrations/main.go
> +        run migrations without applying them - only update current DB. Accepted by all up* commands
в апстриме нет запросов на эту фичу = юзеров нет.
код удалять всегда полезно, не добавлять его изначально - еще лучше

2017-10-12 11:18 UTC, Stepych commented on examples/go-migrations/main.go
> +        run migrations without applying them - only update current DB. Accepted by all up* commands
Эх, значит выпилю((

2017-10-12 13:28 UTC, Stepych commented
@kaey я удалил фичу с `-pretend` в up* командах, посмотри плиз!

2017-10-12 13:33 UTC, kaey approved these changes
вроде ок

2017-10-12 13:37 UTC, merged